<a href="https://colab.research.google.com/github/MuzammilBughio/Machine-Learning-Practice-and-Projects-/blob/main/StudentPerformanceProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analysis of Student Performance:
1.Linear Regression
2.KNN

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nikhil7280/student-performance-multiple-linear-regression")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/nikhil7280/student-performance-multiple-linear-regression/1.archive...

100%|██████████| 48.5k/48.5k [00:00<00:00, 40.6MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/nikhil7280/student-performance-multiple-linear-regression/versions/1

In [48]:
import pandas as pd
df = pd.read_csv(f"{path}/Student_Performance.csv")

In [49]:
#about data
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [52]:
X = df.drop('Performance Index', axis=1)
y = df['Performance Index']
X['Extracurricular Activities'] = pd.get_dummies(X['Extracurricular Activities'] , drop_first=True , dtype=int)

In [43]:
X.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5

In [51]:
# Linear Regression ...

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score , mean_squared_error , root_mean_squared_error
from sklearn.preprocessing import StandardScaler


X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
X_test_scaled = scalar.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled , y_train)
y_pred = model.predict(X_test_scaled)

print("R2 score: " , r2_score(y_test , y_pred))
print("mse: ",mean_squared_error(y_test , y_pred))
print("rmse: ",root_mean_squared_error(y_test , y_pred))

R2 score:  0.9889832909573145
mse:  4.082628398521854
rmse:  2.020551508505006

In [53]:
# Using KKNclassifier ...

from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score , mean_squared_error , root_mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.2 , random_state=42)

pipeline = Pipeline([
     ("scaler", StandardScaler()),
    ("knn", KNeighborsRegressor())
    ])
param_grid ={'knn__n_neighbors' : [3, 5, 7 , 9 ,11]}

model_grid = GridSearchCV( pipeline , param_grid , cv=5 , scoring='r2')

model_grid.fit(X_train , y_train)
y_pred = model_grid.predict(X_test)

print("R2 score: " , r2_score(y_test , y_pred))
print("mse: ",mean_squared_error(y_test , y_pred))
print("rmse: ",root_mean_squared_error(y_test , y_pred))

R2 score:  0.9778457003140724
mse:  8.210053719008263
rmse:  2.8653191303951226